### ISSUE TITLE
不提供一下main程序吗

### ISSUE THREAD

**Issue by Aliang-CN** [xiwd/BPAM#1]
兄弟，可以提供一下main程序吗

**Comment by xiwd** [comment]
__init__.py就是main程序了

**Comment by Aliang-CN** [comment]
噗，没留意看，我以为init是创建包自动生成的文件，空文件来的。

**Comment by xiwd** [comment]
哈哈哈，没事没事~

**Comment by Aliang-CN** [comment]
有一个小问题，在构建矩阵的时候，unique() 里面的count应该初始化为0，要不构建后的mtx会多一行0，也就是说实际上构建后的矩阵的行和列都会比原来的矩阵增加1。
![TIM截图20191129174208](https://user-images.githubusercontent.com/35071040/69859713-a391e800-12cf-11ea-82d8-a8b83c51b9f4.jpg)

**Comment by xiwd** [comment]
噢噢，好的，我修改一下

**Comment by Aliang-CN** [comment]
然后下面这个代码就不用针对为0这一行做处理了
    for i in range(mtx.shape[0]):
        temp = mtx[i]
        if len(temp[temp != 0]) == 0:
            mean_user.append(0)
        else:
            mean_user.append(np.mean(temp[temp != 0]))

**Comment by xiwd** [comment]
这个不影响的，预防这种情况的出现
