### ISSUE TITLE
关于get_kneighbors的小问题

### ISSUE THREAD

**Issue by Aliang-CN** [xiwd/BPAM#2]
兄弟，您好：
我在debug的时候发现了一个小的问题。在get_neighbors里面的，distance, neighbor = neigh.kneighbors(pca_mtx) 对应的是邻近users的s距离和邻近users，s 这个邻近users其实是包括user自己本身。正常来讲，矩阵第一列是user自己本身，因为user跟user自己本身的距离就为0，排在第一位。如果邻近users里面还有其他user距离为0，那么第一列有可能不是user自己本身了。例如53列这个数据。

![微信截图_20191202105020](https://user-images.githubusercontent.com/35071040/69929624-9c025700-14fa-11ea-9a23-a54c6afd590b.png)

下面是我自己修改后的代码，就可以避免这个问题。
distance = distance.tolist()
neighbor = neighbor.tolist()

print(start, end)
ulist = list()     
dlist = list()     
nlist = list()     

for user in range(numberOfUser):
    for i in range(1, k + 1):
        ulist.append(user)
    n_uesrs = neighbor[user]              # 提取user对应的neighbor user
    d_users = distance[user]              # 提取user对应的neighbor user 的distance
    user_index = n_uesrs.index(user)      # 获得user自己在列表对应的index
    del n_uesrs[user_index]
    del d_users[user_index]
    nlist += n_uesrs
    dlist += d_users

**Comment by xiwd** [comment]
嗯嗯，这个我也发现了，没有更新上去
new_neighbor = []
    for i in range(len(neighbor)):
        temp = []
        find = 0
        count = 1
        for j in range(len(neighbor[i])):
            if i != neighbor[i][j]:
                temp.append(neighbor[i][j])
                count += 1
            else:
                find = 1
            if find == 0 and count == len(neighbor[i]):
                break
        #print(i,temp)
        new_neighbor.append(temp)
我用的是这个方法，但是显然你的方法更好一点
