### ISSUE TITLE
关于predict的问题

### ISSUE THREAD

**Issue by Aliang-CN** [xiwd/BPAM#3]
兄弟，您好
有个问题想咨询一下你，在BP网络里面的predict函数，
total += self.input_cells[i] + (attentionRate * attentionWeightKNN[i][j] + self.input_weights[i][j])
为什么不是self.input_cells[i]和attentionWeightKNN相乘的，这样就类似全连接层，如下
total += attentionRate * self.input_cells[i] * attentionWeightKNN[i][j] + self.input_weights[i][j]
我想问一下，你这样设计是出于什么考虑呢？

**Comment by xiwd** [comment]
噗，不好意思啊，写上去的时候写错了，源码是相乘的。抱歉啊！
