### ISSUE TITLE
关于attention机制

### ISSUE THREAD

**Issue by Aliang-CN** [xiwd/BPAM#4]
兄弟，您好。
有个问题想咨询一下你，你在论文上面写着attention机制，我看了你的论文，你这个attention机制指的是每个user的局部权重吗？感觉你这个机制和attention all you need上面的有点不一样，挺新颖的。不过，不适合数据量较大的情况。因为，每个user都要训练一个局部权重，是非常耗时间的。

**Comment by xiwd** [comment]
attention机制可以看成是每个user的全局权重？的确，在大数据集，这种对所有数据集都训练一个全局权重的方式有点耗时间，不过工业界中可能可以尝试分布式的实现。

**Comment by Aliang-CN** [comment]
但愿如此吧
