### ISSUE TITLE
BPAM user rating value duplicated

### ISSUE THREAD

**Issue by shkim-with-code** [xiwd/BPAM#6]
BPAM/read_Data.py

file load '../data/filmtrust/ratings.txt'
But, I find rating value '8.0' in 'mtx_np'

I think User 308 in file, duplicated rating.
Is it right to remove this?

**Comment by xiwd** [comment]
It is fine. Maybe it's the noise in the dataset. Feel shy, I didn't notice it.

**Comment by shkim-with-code** [comment]
Thank you. I am studying this. I removed higher value.

Thank you again for your reply.
